theme: jekyll-theme-tactile
title: Redwater Minor Soccer
email: dirtslayer@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Redwater Minor Soccer is an community organization for kids soccer.
  We run 2 seasons, a summer season and indoor season. Ages 6 - 16.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://redwatersoccer.ca"  # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dirtslayer
github_username:  dirtslayer
