
title: Redwater Minor Soccer
email: darrell@designr8.com

description: >- # this means to ignore newlines until "baseurl:"
  Lets go Rockets!
baseurl: "" # the subpath of your site, e.g. /blog
theme: minima
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
